CREATE DATABASE IF NOT EXISTS ser_sustentavel;
USE ser_sustentavel;

-- 1. TABELA DE USUÁRIOS
-- Guarda os dados cadastrais e a senha encriptada de forma segura (Bcrypt)
CREATE TABLE IF NOT EXISTS USUARIO (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    DATA_NASCIMENTO DATE NOT NULL,
    SENHA_HASH VARCHAR(255) NOT NULL,
    SOBRE_MIM TEXT,
    AVATAR VARCHAR(255),
    DATA_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 2. TABELA DE SESSÃO DE LOGIN 
-- Guarda os tokens JWT. IMPORTANTE: Mudado para TEXT para suportar a criptografia JWT sem cortar o token!
CREATE TABLE IF NOT EXISTS SESSAO_LOGIN (
    ID_SESSAO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    TOKEN_SESSAO TEXT NOT NULL, 
    DATA_HORA_LOGIN DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
);

-- 3. TABELA DE POSTAGEM 
-- Guarda as publicações ecológicas dos usuários
CREATE TABLE IF NOT EXISTS POSTAGEM (
    ID_POSTAGEM INT PRIMARY KEY AUTO_INCREMENT,
    LEGENDA TEXT NOT NULL,       -- Campo TEXT para permitir descrições longas das ações sustentáveis
    CAMINHO_FOTO VARCHAR(255) NOT NULL, -- Guarda a URL ou caminho da imagem do post
    DATA_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    ID_USUARIO INT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
);

-- 4. TABELA DE COMENTÁRIO 
-- Permite a interação de texto entre os usuários nos posts
CREATE TABLE IF NOT EXISTS COMENTARIO (
    ID_COMENTARIO INT PRIMARY KEY AUTO_INCREMENT,
    TEXTO TEXT NOT NULL,
    DATA_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    ID_USUARIO INT NOT NULL,
    ID_POSTAGEM INT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    FOREIGN KEY (ID_POSTAGEM) REFERENCES POSTAGEM(ID_POSTAGEM) ON DELETE CASCADE
);

-- 5. TABELA DE CURTIDA / ECO-CURTIDAS 
-- Registra quais usuários curtiram quais postagens (Evita curtidas duplicadas do mesmo usuário)
CREATE TABLE IF NOT EXISTS CURTIDA (
    ID_CURTIDA INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    ID_POSTAGEM INT NOT NULL,
    DATA_CURTIDA DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    FOREIGN KEY (ID_POSTAGEM) REFERENCES POSTAGEM(ID_POSTAGEM) ON DELETE CASCADE,
    -- Garante que o mesmo usuário não curta o mesmo post mais de uma vez
    CONSTRAINT UQ_USUARIO_POSTAGEM UNIQUE (ID_USUARIO, ID_POSTAGEM)
);

-- =================================================================
-- ADIÇÕES PARA OS NOVOS REQUISITOS (Sprints de Engajamento e Expansão)
-- =================================================================

-- REQUISITO 1: TABELA DE SEGUIDORES (Relacionamento Muitos-para-Muitos autorreferencial)
-- Permite que usuários sigam uns aos outros, bloqueando duplicatas
CREATE TABLE IF NOT EXISTS SEGUIDOR (
    ID_SEGUIDOR INT PRIMARY KEY AUTO_INCREMENT,
    ID_SEGUIDOR_USUARIO INT NOT NULL, -- Quem executa a ação de seguir
    ID_SEGUIDO_USUARIO INT NOT NULL,  -- Quem está sendo seguido
    DATA_SEGUIDO DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_SEGUIDOR_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    FOREIGN KEY (ID_SEGUIDO_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    -- Impede seguir a mesma pessoa duas vezes
    CONSTRAINT UQ_SEGUIDOR_SEGUIDO UNIQUE (ID_SEGUIDOR_USUARIO, ID_SEGUIDO_USUARIO)
);

-- REQUISITO 3: TABELA DE TÓPICOS DO FÓRUM
-- Estrutura para debates sobre temas ecológicos (usada no Requisito 2 de busca global)
CREATE TABLE IF NOT EXISTS TOPICO_FORUM (
    ID_TOPICO INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(150) NOT NULL,
    CONTEUDO TEXT NOT NULL,
    DATA_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    ID_USUARIO INT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
);

-- REQUISITO 4: TABELA DE RESPOSTAS DO FÓRUM
-- Permite as interações dentro de cada tópico aberto no fórum
CREATE TABLE IF NOT EXISTS RESPOSTA_FORUM (
    ID_RESPOSTA INT PRIMARY KEY AUTO_INCREMENT,
    CONTEUDO TEXT NOT NULL,
    DATA_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    ID_TOPICO INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    FOREIGN KEY (ID_TOPICO) REFERENCES TOPICO_FORUM(ID_TOPICO) ON DELETE CASCADE,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
);

-- REQUISITO 5: TABELA DE LOG HISTÓRICO DE PONTUAÇÃO (Gamificação)
-- Registra cada ganho de ponto individualmente. Evita perdas de dados e calcula o saldo no perfil
CREATE TABLE IF NOT EXISTS LOG_PONTUACAO (
    ID_LOG INT PRIMARY KEY AUTO_INCREMENT,
    QUANTIDADE_PONTOS INT NOT NULL,
    MOTIVO VARCHAR(100) NOT NULL, -- Ex: "Nova Publicação Ecológica", "Check-in de Hábito"
    DATA_CREDITO DATETIME DEFAULT CURRENT_TIMESTAMP,
    ID_USUARIO INT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
);

-- REQUISITO 6: TABELA DE PONTOS SUSTENTÁVEIS (Mapa Interativo)
-- Armazena os locais físicos de descarte, cooperativas ou feiras
CREATE TABLE IF NOT EXISTS PONTO_SUSTENTAVEL (
    ID_PONTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(150) NOT NULL,
    TIPO VARCHAR(100) NOT NULL,     -- Ex: "Reciclagem de Eletrônicos", "Ponto de Orgânicos"
    ENDERECO VARCHAR(255) NOT NULL,
    LATITUDE DOUBLE NOT NULL,         -- Armazenados como DOUBLE para precisão em mapas Leaflet/Google
    LONGITUDE DOUBLE NOT NULL
);

-- REQUISITO 7: TABELA DE REGISTRO DE HÁBITOS DIÁRIOS
-- Monitora os hábitos repetitivos marcados pelo usuário no dia a dia
CREATE TABLE IF NOT EXISTS HABITO_DIARIO (
    ID_HABITO INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_HABITO VARCHAR(100) NOT NULL, -- Ex: "Economia de Água", "Uso de Eco-bag"
    CONCLUIDO_EM DATETIME DEFAULT CURRENT_TIMESTAMP,
    ID_USUARIO INT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
);
